


CREATE TABLE avg_response_per_borough (
    ID FLOAT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT   NOT NULL,
    CONSTRAINT pk_avg_response_per_borough PRIMARY KEY (
        ID
     )
);

CREATE TABLE Bronx (
    ID FLOAT   NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE FLOAT   NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE FLOAT   NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY FLOAT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Bronx PRIMARY KEY (
        ID
     )
);

CREATE TABLE Brooklyn (
    ID FLOAT NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY FLOAT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Brooklyn PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_Br (
    ID FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT NOT NULL,
    CONSTRAINT pk_initial_severity_Br PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_Bx (
    ID FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT NOT NULL,
    CONSTRAINT pk_initial_severity_Bx PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_M (
    ID FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT NOT NULL,
    CONSTRAINT pk_initial_severity_M PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_NYC (
    ID FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT NOT NULL,
    CONSTRAINT pk_initial_severity_NYC PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_Q (
    ID FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT NOT NULL,
    CONSTRAINT pk_initial_severity_Q PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_SI (
    ID FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT NOT NULL,
    CONSTRAINT pk_initial_severity_SI PRIMARY KEY (
        ID
     )
);

CREATE TABLE Manhattan (
    ID FLOAT NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Manhattan PRIMARY KEY (
        ID
     )
);

CREATE TABLE NYC (
    ID FLOAT NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY FLOAT NOT NULL,
    BOROUGH VARCHAR(25)   NOT NULL,
    CONSTRAINT pk_NYC PRIMARY KEY (
        ID
     )
);

CREATE TABLE Queens (
    ID FLOAT NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY FLOAT NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Queens PRIMARY KEY (
        ID
     )
);

CREATE TABLE Staten_Island (
    ID FLOAT NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE FLOAT NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY FLOAT NOT NULL,
    BOROUGH VARCHAR(25)   NOT NULL,
    CONSTRAINT pk_Staten_Island PRIMARY KEY (
        ID
     )
);


CREATE TABLE avg_response_before_covid (
    ID FLOAT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT   NOT NULL,
    CONSTRAINT pk_avg_response_before_covid PRIMARY KEY (
        ID
     )
);

CREATE TABLE avg_response_after_covid (
    ID FLOAT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS FLOAT   NOT NULL,
    CONSTRAINT pk_avg_response_after_covid PRIMARY KEY (
        ID
     )
);
