-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

-- Modify this code to update the DB schema diagram.
-- To reset the sample schema, replace everything with
-- two dots ('..' - without quotes).

CREATE TABLE avg_response_per_borough (
    ID INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS INT   NOT NULL,
    CONSTRAINT pk_avg_response_per_borough PRIMARY KEY (
        ID
     )
);

CREATE TABLE Bronx (
    ID INT   NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Bronx PRIMARY KEY (
        ID
     )
);

CREATE TABLE Brooklyn (
    ID INT   NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Brooklyn PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_Br (
    ID INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS INT   NOT NULL,
    CONSTRAINT pk_initial_severity_Br PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_Bx (
    ID INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS INT   NOT NULL,
    CONSTRAINT pk_initial_severity_Bx PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_M (
    ID INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS INT   NOT NULL,
    CONSTRAINT pk_initial_severity_M PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_NYC (
    ID INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS INT   NOT NULL,
    CONSTRAINT pk_initial_severity_NYC PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_Q (
    ID INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS INT   NOT NULL,
    CONSTRAINT pk_initial_severity_Q PRIMARY KEY (
        ID
     )
);

CREATE TABLE initial_severity_SI (
    ID INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    AVERAGE_RESPONSE_SECONDS INT   NOT NULL,
    CONSTRAINT pk_initial_severity_SI PRIMARY KEY (
        ID
     )
);

CREATE TABLE Manhattan (
    ID INT   NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Manhattan PRIMARY KEY (
        ID
     )
);

CREATE TABLE NYC (
    ID INT   NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY INT   NOT NULL,
    BOROUGH VARCHAR(25)   NOT NULL,
    CONSTRAINT pk_NYC PRIMARY KEY (
        ID
     )
);

CREATE TABLE Queens (
    ID INT   NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY INT   NOT NULL,
    BOROUGH VARCHAR(15)   NOT NULL,
    CONSTRAINT pk_Queens PRIMARY KEY (
        ID
     )
);

CREATE TABLE Staten_Island (
    ID INT   NOT NULL,
    INCIDENT_DATETIME TIMESTAMP   NOT NULL,
    INITIAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FINAL_SEVERITY_LEVEL_CODE INT   NOT NULL,
    FIRST_ASSIGNMENT_DATETIME TIMESTAMP   NOT NULL,
    INCIDENT_RESPONSE_SECONDS_QY INT   NOT NULL,
    BOROUGH VARCHAR(25)   NOT NULL,
    CONSTRAINT pk_Staten_Island PRIMARY KEY (
        ID
     )
);